/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThuyVT
 */
public class QLOD extends javax.swing.JFrame implements Runnable {

    List<DonHang> listDonHang = new ArrayList<>();
    DefaultTableModel defaultTable = new DefaultTableModel();

    /**
     * Creates new form QLOD
     */
    public QLOD() {
        initComponents();
        defaultTable = (DefaultTableModel) tblDanhSach.getModel();

        // Tao danh sach mac dinh 5 phan tu
        DonHang dh1 = new DonHang("Hong tra sua", 2, "Thach", "", true);
        DonHang dh2 = new DonHang("Hong tra sua", 4, "Trân châu den", "1231", true);
        DonHang dh3 = new DonHang("Sua tuoi tran chau duong den", 4, "Trân châu trang", "", true);
        DonHang dh4 = new DonHang("Sinh to xoài", 4, "Thach", "abc", true);
        DonHang dh5 = new DonHang("Sinh to xoài", 6, "Thach", "12312", true);
        listDonHang.add(dh1);
        listDonHang.add(dh2);
        listDonHang.add(dh3);
        listDonHang.add(dh4);
        listDonHang.add(dh5);

        // Do danh sach len bang
        doDuLieuLenBang();

        // Hien thi du lieu phan tu thu 4 len form
        doDuLieuLenForm(listDonHang.get(3));

        // Khoi tao luong chay chu
        Thread t1 = new Thread(this);
        t1.start();
    }

    private void doDuLieuLenBang() {
        // Do du lieu tu dong dau tien
        defaultTable.setRowCount(0);
        // Duyet tung phan tu do du lieu len bang
        for (DonHang dh : listDonHang) {
            defaultTable.addRow(new Object[]{dh.getMon(), dh.getSoLuong(),
                dh.getTopping(), dh.getGhiChu(), dh.isThanhToan()});
        }
    }

    private void doDuLieuLenForm(DonHang dh) {
        // Do du lieu len combobox
        cboMon.setSelectedItem(dh.getMon());
        // Do du lieu len textField So luong 
        txtSoLuong.setText(String.valueOf(dh.getSoLuong()));
        if (dh.getTopping().equals("Trân châu den")) {
            rdoTTD.setSelected(true);
        } else if (dh.getTopping().equals("Trân châu trang")) {
            rdoTTT.setSelected(true);
        } else if (dh.getTopping().equals("Thach")) {
            rdoT.setSelected(true);
        } else {
            rdoTTD.setSelected(false);
            rdoTTT.setSelected(false);
            rdoT.setSelected(false);
        }
    }

    // Lay du lieu tu form
    private DonHang layDuLieuTuForm() {
        String topping = "";
        if (rdoTTD.isSelected()) {
            topping = "Trân châu den";
        } else if (rdoTTT.isSelected()) {
            topping = "Trân châu trang";
        } else if (rdoT.isSelected()) {
            topping = "Thach";
        }
//        DonHang dh = new DonHang(cboMon.getSelectedItem().toString(),
//                Integer.parseInt(txtSoLuong.getText()),
//                rdoTTD.isSelected() ? "Trân châu den" : rdoTTT.isSelected() ? "Trân châu trang"
//                : rdoT.isSelected() ? "Thach" : "", ghiChu, rootPaneCheckingEnabled);
        int soluong = 0;
        try {
            soluong = Integer.parseInt(txtSoLuong.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "So luong phai la so nguyen duong");
        }
        DonHang dh = new DonHang(cboMon.getSelectedItem().toString(),
                soluong, topping, txtGhiChu.getText(), chkThanhToan.isSelected());
        return dh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboMon = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chkThanhToan = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        rdoTTD = new javax.swing.JRadioButton();
        rdoTTT = new javax.swing.JRadioButton();
        rdoT = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        btnGhi = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 204, 204));
        txtTitle.setText("QUAN LY DON DAT HANG ");

        jLabel3.setText("Món");

        cboMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hong tra sua", "Sua tuoi tran chau duong den", "Sinh to xoài" }));

        jLabel4.setText("So luong");

        jLabel5.setText("Trang thai");

        chkThanhToan.setText("Da thanh toan");

        jLabel6.setText("Topping");

        buttonGroup1.add(rdoTTD);
        rdoTTD.setText("Trân châu den");

        buttonGroup1.add(rdoTTT);
        rdoTTT.setText("Trân châu trang");
        rdoTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTTTActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoT);
        rdoT.setText("Thach");

        jLabel7.setText("Ghi chú");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Món", "So luong", "Topping", "Ghi chú", "Trang thai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSach);

        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnDoc.setText("Doc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sap xep");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboMon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkThanhToan)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoTTD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rdoTTT)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDoc)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGhi)))
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSapXep)
                    .addComponent(btnTimKiem))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSapXep))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua)
                            .addComponent(btnTimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addGap(15, 15, 15)
                        .addComponent(btnGhi))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rdoTTD)
                            .addComponent(rdoT))
                        .addGap(11, 11, 11)
                        .addComponent(rdoTTT)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(chkThanhToan)
                            .addComponent(btnDoc))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTTTActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblDanhSach.getSelectedRow();
        // Lay doi tuong thong qua index
        DonHang donHang = listDonHang.get(rowIndex);
        // do du lieu cua doi tuong len fom
        doDuLieuLenForm(donHang);
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String format = "[1-9]+";//[1-9]+
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phai dien so luong");
        } else if (!txtSoLuong.getText().trim().matches(format)) {
            JOptionPane.showMessageDialog(this, "So luong phai la so nguyen duong");
        } else {
            // Lay du lieu tu form
            DonHang donhang = layDuLieuTuForm();
            // them doi tuong vao danh sach
            listDonHang.add(donhang);
            // Do danh sach moi len bang
            doDuLieuLenBang();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // Lay vi tri doi truong da chon tren bang
        String format = "[1-9]+";//[1-9]+
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phai dien so luong");
        } else if (!txtSoLuong.getText().trim().matches(format)) {
            JOptionPane.showMessageDialog(this, "So luong phai la so nguyen duong");
        } else {
            int rowIndex = tblDanhSach.getSelectedRow();
            // Lay duoc du lieu doi tuong duoc sua tren form
            DonHang dh = layDuLieuTuForm();
            listDonHang.set(rowIndex, dh);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int rowIndex = tblDanhSach.getSelectedRow();
        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Chon doi tuong can xoa");
        } else {
            // 0: Yes; 1: No; 2: Cancel
            int confirm = JOptionPane.showConfirmDialog(this, "Co chac chan muon xoa khong");
            if (confirm == 0) {
                listDonHang.remove(rowIndex);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        try {
            // TODO add your handling code here:
            // Mo ghi file co ban
            FileOutputStream fos = new FileOutputStream("D:\\qlod.txt");
            ObjectOutputStream os = new ObjectOutputStream(fos);

            // Ghi danh sach vao file
            os.writeObject(listDonHang);

            // Dong luong ghi file
            os.close();
            fos.close();

            JOptionPane.showMessageDialog(this, "Ghi file thanh cong");

        } catch (FileNotFoundException ex) {
            Logger.getLogger(QLOD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QLOD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        try {
            // TODO add your handling code here:
            FileInputStream fis = new FileInputStream("D:\\qlod.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);

            listDonHang = (List<DonHang>) ois.readObject();
            if (listDonHang != null && !listDonHang.isEmpty()) {
                doDuLieuLenBang();
            }

            // Dong luong doc file
            ois.close();
            fis.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(QLOD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QLOD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLOD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDocActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
        listDonHang.sort(Comparator.comparing(DonHang::getMon));
        // Do danh sach moi len bang
        doDuLieuLenBang();
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        // C1: Dung stream

//        List<DonHang> dsCanTim = listDonHang.stream().filter(item -> item.getMon().
//                equalsIgnoreCase(cboMon.getSelectedItem().toString())).collect(Collectors.toList());
//        Do du lieu tu dong dau tien
//        defaultTable.setRowCount(0);
//        // Duyet tung phan tu do du lieu len bang
//        for (DonHang dh : dsCanTim) {
//            defaultTable.addRow(new Object[]{dh.getMon(), dh.getSoLuong(),
//                dh.getTopping(), dh.getGhiChu(), dh.isThanhToan()});
//        }

        // C2: Duyet danh sach
        List<DonHang> dsCanTim = new ArrayList<>();
        for (DonHang dh : listDonHang) {
            if (dh.getMon().equalsIgnoreCase(cboMon.getSelectedItem().toString())) {
                dsCanTim.add(dh);
            }
        }
        if (dsCanTim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khong co du lieu can tim");
        } else {
            defaultTable.setRowCount(0);
            // Duyet tung phan tu do du lieu len bang
            for (DonHang dh : dsCanTim) {
                defaultTable.addRow(new Object[]{dh.getMon(), dh.getSoLuong(),
                    dh.getTopping(), dh.getGhiChu(), dh.isThanhToan()});
            }
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLOD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboMon;
    private javax.swing.JCheckBox chkThanhToan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdoT;
    private javax.swing.JRadioButton rdoTTD;
    private javax.swing.JRadioButton rdoTTT;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                // Cat du dau tien trong tieu de
                String chuDau = txtTitle.getText().substring(0, 1);
                System.out.println(chuDau);
                // Lap chu dau vao duoi
                txtTitle.setText(txtTitle.getText().substring(1) + chuDau);
                System.out.println(txtTitle.getText());

                // nghi 1000
                Thread.sleep(1000);

            } catch (InterruptedException ex) {
                break;
            }

        }

    }
}
